PAY-331 feat: Commeted the SSM secrets

diff --git a/amplify.yml b/amplify.yml
--- a/amplify.yml
+++ b/amplify.yml
@@ -6,29 +6,29 @@ frontend:
       commands:
         - |
           npm ci
-          get_secret() {
-            BASE_PATH="/amplify/shared/${AWS_APP_ID}"
+          # get_secret() {
+          #   BASE_PATH="/amplify/${AWS_APP_ID}"
 
-            aws ssm get-parameter \
-              --name "${BASE_PATH}/$1" \
-              --with-decryption \
-              --query "Parameter.Value" \
-              --output text
-          }
+          #   aws ssm get-parameter \
+          #     --name "${BASE_PATH}/$1" \
+          #     --with-decryption \
+          #     --query "Parameter.Value" \
+          #     --output text
+          # }
 
-          ssm_secrets=(
-            "AUTH_MICROSOFT_ENTRA_ID_ID"
-            "AUTH_MICROSOFT_ENTRA_ID_SECRET"
-            "AUTH_MICROSOFT_ENTRA_ID_ISSUER"
-            "NEXTAUTH_SECRET"
-          )
+          # ssm_secrets=(
+          #   "AUTH_MICROSOFT_ENTRA_ID_ID"
+          #   "AUTH_MICROSOFT_ENTRA_ID_SECRET"
+          #   "AUTH_MICROSOFT_ENTRA_ID_ISSUER"
+          #   "NEXTAUTH_SECRET"
+          # )
 
-          for secret in "${ssm_secrets[@]}"; do
-            if ! get_secret "$secret" >/dev/null 2>&1; then
-              echo "Error: Secret '$secret' not found in SSM Parameter Store at path '/amplify/shared/${AWS_APP_ID}/$secret'."
-              exit 1
-            fi
-          done
+          # for secret in "${ssm_secrets[@]}"; do
+          #   if ! get_secret "$secret" >/dev/null 2>&1; then
+          #     echo "Error: Secret '$secret' not found in SSM Parameter Store at path '/amplify/shared/${AWS_APP_ID}/$secret'."
+          #     exit 1
+          #   fi
+          # done
 
     build:
       commands:
